### ISSUE TITLE
Wrong parameters when executing a dry run

### ISSUE THREAD

**Issue by ostefano** [BrianGallew/cassandra_range_repair#46]
Hi all,

seems like C* 3 doesn't play well yet with the repair script.
Attached the error (python 2.7).

Cheers,
Stefano

```
root@node5:~# ./range_repair.py -H localhost --inc --par --verbose --dry-run
INFO       2016-07-04 09:05:07,494 get_ring_tokens      line: 135 : running nodetool ring, this will take a little bit of time
INFO       2016-07-04 09:05:12,456 get_ring_tokens      line: 157 : Found 3328 tokens
INFO       2016-07-04 09:05:12,508 repair               line: 353 : [1/256] repairing range (+09208181131779273900, -09221551068845876240) in 100 steps for keyspace <all>
Traceback (most recent call last):
  File "./range_repair.py", line 475, in <module>
    main()
  File "./range_repair.py", line 471, in main
    repair(options)
  File "./range_repair.py", line 364, in repair
    r.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
TypeError: sequence item 4: expected string, int found
0001/1/256 0002/1/256 0003/1/256 0004/1/256 0005/1/256 0006/1/256 0007/1/256 0008/1/256 0009/1/256 0010/1/256 0011/1/256 0012/1/256 0013/1/256 0014/1/256 0015/1/256 0016/1/256 0017/1/256 0018/1/256 0019/1/256 0020/1/256 0021/1/256 0022/1/256 0023/1/256 0024/1/256 0025/1/256 0026/1/256 0027/1/256 0028/1/256 0029/1/256 0030/1/256 0031/1/256 0032/1/256 0033/1/256 0034/1/256 0035/1/256 0036/1/256 0037/1/256 0038/1/256 0039/1/256 0040/1/256 0041/1/256 0042/1/256 0043/1/256 0044/1/256 0045/1/256 0046/1/256 0047/1/256 0048/1/256 0049/1/256 0050/1/256 0051/1/256 0052/1/256 0053/1/256 0054/1/256 0055/1/256 0056/1/256 0057/1/256 0058/1/256 0059/1/256 0060/1/256 0061/1/256 0062/1/256 0063/1/256 0064/1/256 0065/1/256 0066/1/256 0067/1/256 0068/1/256 0069/1/256 0070/1/256 0071/1/256 0072/1/256 0073/1/256 0074/1/256
```

**Comment by ostefano** [comment]
My mistake, was just a tiny bug on the dry_run execution path.
Will soon open a pull request with the fix.
